name: 'Hello Work'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: # id of input
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'The time'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}